### ISSUE TITLE
error Fatal error: Declaration of Gamification\Group\Groups::load() must be compatible with Prism\Database\ArrayObject::load(array $options = Array) in /libraries/Gamification/Group/Groups.php on line 23

### ISSUE THREAD

**Issue by nehemiash** [ITPrism/GamificationPlatform#18]
hi, when I enter to the groups, badges, ranks or levels in component appears an error "Fatal error: Declaration of Gamification\Group\Groups::load() must be compatible with Prism\Database\ArrayObject::load(array $options = Array) in /libraries/Gamification/Group/Groups.php on line 23"
can you help me?

**Comment by ITPrism** [comment]
Hi,
Current version is not compatible with Prism Library 1.13 and I have to fix it.
You can see how to fix in the distribution.
https://github.com/ITPrism/GamificationDistribution/tree/develop/libraries/Gamification

I am going to publish the new version soon.

**Comment by ITPrism** [comment]
Fixed! :)

**Comment by dmware** [comment]
Awesome! Thanks :)

**Comment by ITPrism** [comment]
Are you sure it is same error?
You have to install the new version over old one. The installer will create newest database columns and tables.
I guess, it is missing some columns. You can enable Joomla debug to get more information about the error.

If you have uninstall it, you will have to remove database tables manually. 
The tables have prefix _gfy_.

Then, install the extension again.
